# Linear Algebra — Khan Academy

Notebook for linear algebra computations with **NumPy** and **Pandas**.

In [1]:
import numpy as np
import pandas as pd

print(f"NumPy  : {np.__version__}")
print(f"Pandas : {pd.__version__}")
print("\n✅ Ready to go!")

NumPy  : 2.4.3
Pandas : 3.0.1

✅ Ready to go!


## Unit 1: Vectors and Space

### Lesson 1: Vectors

Vector -> Magnitude & direction

#### Vector representation

$$ \vec{x} = \begin{bmatrix} x_1 \\ x_2 \\ \vdots \\ x_n \end{bmatrix} \space , \space \vec{y} = \begin{bmatrix} y_1 \\ y_2 \\ \vdots \\ y_n \end{bmatrix} $$

#### Vectors addition

$$ \vec{x} + \vec{y} = \begin{bmatrix} x_1 + y_1 \\ x_2 + y_2 \\ \vdots \\ x_n + y_n \end{bmatrix} $$

#### Vectors multiplication by scalars

$$ \lambda \cdot \vec{x} = \begin{bmatrix} \lambda \cdot x_1 \\ \lambda \cdot x_2 \\ \vdots \\ \lambda \cdot x_n \end{bmatrix} $$

#### Unit vectors in $\reals^3$

$$ \hat{i} = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix} \space , \space \hat{j} = \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix} \space , \space \hat{k} = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix} $$

$$
\vec{v} = 
\begin{bmatrix} 
v_1 \\ 
v_2 \\ 
v_3 
\end{bmatrix} = 
v_1 \space \hat{i} + 
v_2 \space \hat{j} + 
v_3 \space \hat{k} 
$$

#### Lines parametrization

$$
L = 
\left\{
\vec{x} + t \cdot \vec{v} 
\space
| 
\space
t \in \reals
\right\}
$$

#### Lines that use two other vectors

$$
L =
\left\{
\vec{P_1} + t \cdot
\begin{pmatrix}
\vec{P_1} - \vec{P_2}
\end{pmatrix}
\space | \space
t \in \reals
\right\}
$$

### Lesson 2: Linear Combinations and spans

#### Linear Combinations

$$ \vec{v_1}, \vec{v_2}, \dots, \vec{v_n} \in \reals^n \space , \space
c_1, c_2, \dots, c_n \in \reals $$

$$ c_1 \vec{v_1} + c_2 \vec{v_2} + \dots + c_n \vec{v_n} $$

#### Span of non-colinear vectors

$$ \vec{a}, \vec{b} \in \reals^2 \space , \space \vec{b} \neq c \vec{a} $$

$$ Span(\vec{a}, \vec{b}) = \reals^2 $$

### Lesson 3: Linear dependence and independence

#### Linear dependence

When one vector of the set **can** be represented by a linear combination of the others

$$ \vec{v} = c_1 \vec{x_1} + c_2 \vec{x_2} $$

or formally:

$$ c_1 \vec{v_1} + c_2 \vec{v_2} + \dots + c_n \vec{v_n} = \vec{0}
\space ; \space \exists \space c_i \neq 0 \space | \space i \in \left\{ 1, 2, \dots, n \right\} $$

#### Linear independence

When any vector of the set **can't** be represented by a linear combination of the others

$$ \vec{v} \neq c_1 \vec{x_1} + c_2 \vec{x_2} $$

or formally:

$$ c_1 \vec{v_1} + c_2 \vec{v_2} + \dots + c_n \vec{v_n} = \vec{0} 
\space ; \space c_1 = c_2 = \dots = c_n = 0 $$

### Lesson 4: Subspaces and the basis for a subspace

#### Linear subspace

$V$ is a subset of $\reals^n$, if:

- $V$ contains $\vec{0} \space | \space \vec{0} = \begin{bmatrix} 0, \space 0, \dots, \space 0 \end{bmatrix}^T $

- $\vec{x} \in V \rightarrow \lambda \vec{x} \in V \space | \space \lambda \in \reals$ (closure under scalar multiplication)

- $ \vec{a} \in V \space , \space \vec{b} \in V \space \rightarrow \space \vec{a} + \vec{b} \in V $ (closure under addition)

#### Basis of a subpsace

A Span is the set of all possible combinations of the vectors that form the span (basis).

$$ V= Span(\vec{v_1}, \vec{v_2}, \dots, \vec{v_n})$$

$$ S = \left\{\vec{v_1}, \vec{v_2}, \dots, \vec{v_n}\right\} \rightarrow S \space is \space a \space basis \space for \space V $$

A Basis is the **minimum** set of vectors that spans the subspace, therefore the vectors of the basis are linearly independent.

#### Standard Basis

$$ T = \left\{ \begin{bmatrix} 1 \\ 0 \end{bmatrix} , \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right\} $$

$$ \hat{i} = \begin{bmatrix} 1 \\ 0 \end{bmatrix} \space , \space \hat{j} = \begin{bmatrix} 0 \\ 1 \end{bmatrix} $$

### Lesson 5: Vector dot and cross products

Given vectors $ \vec{a}, \vec{b}, \vec{c} \in \reals^n$ and $ \lambda \in \reals $

$$
\vec{a} = \begin{bmatrix} a_1 \\ a_2 \\ \vdots \\ a_n \end{bmatrix} \space , \space
\vec{b} = \begin{bmatrix} b_1 \\ b_2 \\ \vdots \\ b_n \end{bmatrix} \space , \space
\vec{c} = \begin{bmatrix} c_1 \\ c_2 \\ \vdots \\ c_n \end{bmatrix}
$$

#### Addition

$$
\vec{a} + \vec{b} = \begin{bmatrix} a_1 + b_1 \\ a_2 + b_2 \\ \vdots \\ a_n + b_n \end{bmatrix}
$$

#### Scalar Multiplication

$$
\lambda \vec{a} = \begin{bmatrix} \lambda a_1 \\ \lambda a_2 \\ \vdots \\ \lambda a_n \end{bmatrix}
$$

#### Dot Product

$$
\vec{a} \cdot \vec{b} 
= \begin{bmatrix} a_1 \\ a_2 \\ \vdots \\ a_n \end{bmatrix} \cdot
\begin{bmatrix} b_1 \\ b_2 \\ \vdots \\ b_n \end{bmatrix}
= a_1 b_1 + a_2 + b_2 + \dots + a_n b_n
$$

$$
\vec{a} \cdot \vec{b} = \vec{b} \cdot \vec{a}
$$

$$
\begin{pmatrix} \vec{a} + \vec{b} \end{pmatrix} \cdot \vec{c} =
\begin{pmatrix} \vec{a} \cdot \vec{c} + \vec{b} \cdot \vec{c} \end{pmatrix}
$$

$$
\begin{pmatrix} \lambda \vec{a} \end{pmatrix} \cdot \vec{b} =
\lambda \begin{pmatrix} \vec{a} \cdot \vec{b} \end{pmatrix}
$$

#### Magnitude

$$
\|\vec{a}\| = \sqrt{a_1^2 + a_2^2 + \dots + a_n^2}
$$

$$
\|\vec{a}\| = \sqrt{\vec{a} \cdot \vec{a}}
\space \rightarrow \space
\|\vec{a}\|^2 = \vec{a} \cdot \vec{a}
$$

#### Cauchy-Swartz Inequality

$$
\vec{x} \space , \space \vec{y} \in \reals^n
$$

$$
|\vec{x} \cdot \vec{y}| \leq \|\vec{x}\| \|\vec{y}\|
$$

$$
|\vec{x} \cdot \vec{y}| = \|\vec{x}\| \|\vec{y}\| \iff \vec{x} = \lambda \vec{y}
$$

#### Triangle Inequality

$$
\|\vec{x} + \vec{y}\| \leq \|\vec{x}\| + \|\vec{y}\| 
$$

$$
\|\vec{x} + \vec{y}\| = \|\vec{x}\| + \|\vec{y}\| \iff \vec{x} = \lambda \vec{y} \quad \text{for} \quad \lambda \ge 0
$$

#### Angle Between Vectors

$$
\cos{\theta} = \frac{\vec{x} \cdot \vec{y}}{\|\vec{x}\| \|\vec{y}\|}
$$

#### Perpendicular Vectors

Given two non-zero vectors $\vec{x}$ and $\vec{y}$ in $\reals^n$

$$
\vec{x} \perp \vec{y} \iff \vec{x} \cdot \vec{y} = 0
$$

If two vectors are perpendicular, they are orthogonal to each other. Also, the zero vector $\vec{0}$ is **orthogonal** to all other vectors, but perpendicular to none.

#### General Plane Formula

$$
Ax + By + Cz = D
$$

#### Cross Product

$$
\vec{x} \times \vec{y} = \begin{bmatrix} x_2 y_3 - x_3 y_2 \\ x_3 y_1 - x_1 y_3 \\ x_1 y_2 - x_2 y_1 \end{bmatrix}
$$

The resultant cross product vector is orthogonal two the first two vectors.

In [3]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

cp = np.cross(x, y)
print(cp)

[-3  6 -3]


In [4]:
print(np.dot(x, cp))
print(np.dot(y, cp))

0
0


#### Cross product and sin of angle

$$
\|\vec{x} \times \vec{y} \| = \|\vec{x}\| \|\vec{y}\| \sin\theta
$$

$$
\|\vec{x} \times \vec{y}\| = 0; \space \text{for} \space \theta = 0 \space \text{(colinear)}
$$

#### Area of the parallelogram formed by two vectors

$$
Area = \|\vec{x} \times \vec{y}\| = \|\vec{x}\| \|\vec{y}\| \sin \theta
$$

#### Triple cross product of three vectors

$$
\vec{a} \times \begin{pmatrix} \vec{b} \times \vec{c} \end{pmatrix} = \begin{pmatrix} \vec{a} \cdot \vec{c} \end{pmatrix} \vec{b} - \begin{pmatrix} \vec{a} \cdot \vec{b} \end{pmatrix} \vec{c}
$$

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

In [3]:
print(np.cross(a, np.cross(b, c)))

[-24  -6  12]


In [4]:
print(np.dot(a, c) * b - np.dot(a, b) * c)

[-24  -6  12]


#### Normal vector from plane equation

Given, the plane equation:

$$ Ax + By + Cz = D $$

The normal vector will be:

$$ \vec{n} = A\hat{i} + B\hat{j} + C\hat{k} = \begin{bmatrix} A \\ B \\ C \end{bmatrix} $$

#### Distance from a point to a plane

Given the point $P_0$

$$ P_0 = \begin{bmatrix} x_0 \\ y_0 \\ z_0 \end{bmatrix}

$$
distance = \frac{A x_0 + B y_0 + C z_0 - D}{\sqrt{A^2 + B^2 + C^2}}
$$

#### Distance between planes

In order for two planes to have distance, they need to be parallel to each other

$$ P_1 \parallel P_2 \rightarrow \vec{n_1} = \vec{n_2} $$

Exercise:

If the distance between the plane $ Ax - 2y + z = d $ and the plane containing the lines $ \frac{x-1}{2} = \frac{y-2}{3} = \frac{z-3}{4} $ and $ \frac{x-2}{3} = \frac{y-3}{4} = \frac{z-4}{5} $ is $ \sqrt{6} $ then $ |d| $ is ?

Solution:

Lets compute three points in the second plane by finding points that satisfy the lines equation

$$
p_1 = \begin{pmatrix} 1, 2, 3 \end{pmatrix}, \quad
p_2 = \begin{pmatrix} 3, 5, 7 \end{pmatrix}, \quad
p_3 = \begin{pmatrix} 2, 3, 4 \end{pmatrix}
$$

Using the points, define two vectors in the plane:

$$ \vec{a} = (3 - 1)\hat{i} + (5 - 2)\hat{j} + (7 - 3)\hat{k} = 2\hat{i} + 3\hat{j} + 4\hat{k} $$

$$ \vec{b} = (2 - 1)\hat{i} + (3 - 2)\hat{j} + (4 - 3)\hat{k} = \hat{i} + \hat{j} + \hat{k} $$

Compute the normal product of these two vectors:

In [7]:
a = np.array([2, 3, 4])
b = np.array([1, 1, 1])

n_2 = np.cross(a, b)
print(n_2)

[-1  2 -1]


Use the normal vector, a variable point and dot product to find the second plane equation:

$$ p = (x, y, z) $$

$$ \vec{v} = p - p_2 = (x - 3)\hat{i} + (y - 5)\hat{j} + (z - 7)\hat{k} $$

$$ \vec{n_2} \cdot \vec{v} = 0 $$

$$ -1(x-3) + 2(y - 5) -1(z - 7) = 0 $$

$$ 3 - x + 2y - 10 + 7 - z = 0 $$

$$ P_2: x - 2y + z = 0 $$

The first plane and the second plane need to be parallel as they have a distance between each other, so they share the normal vector:

$$ P_1: Ax - 2y + z = d $$

$$ P_2: x - 2y +z = 0 $$

$$ \Rightarrow A = 1 $$

Now, to compute the distance we use $p_1$ of the plane 2 and the formula of distance from a point to a plane:

$$ distance = \frac{1 \times 1 + (-2) \times 2 + 1 \times 3 - d}{\sqrt{1^2 + (-2)^2 + 1^2}} $$

$$ \sqrt{6} = \frac{-d}{\sqrt{6}} $$

$$ d = -6 $$

$$ \therefore  |d| = 6 $$

### Lesson 6: Matrices for solving systems by elimination

#### Reduced Row Echelon Form

A matrix is in **Reduced Row Echelon Form (RREF)** if it satisfies the following conditions:
1. All zero rows are at the bottom of the matrix.
2. The leading entry (the first non-zero entry) in each non-zero row is 1 (called a **pivot**).
3. The pivot of each row is to the right of the pivot in the row above it.
4. Each column containing a pivot has zeros in all its other entries.

**Example RREF Matrix:**

$$
\begin{bmatrix}
1 & 0 & 3 & 0 \\
0 & 1 & 2 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

In this matrix:
- Pivots are at positions $(1,1)$, $(2,2)$, and $(3,4)$.
- All pivot columns have zeros elsewhere.
- The zero-entry column (column 3) shows a free variable.

#### Solving a System of Equations with RREF

To solve a system of equations, we represent it as an **augmented matrix** and use Gauss-Jordan elimination to reach its RREF.

**System of Equations:**
$$
\begin{cases}
x + 2y + z = 1 \\
0x + y - z = 3 \\
2x + 4y + 2z = 2
\end{cases}
$$

**1. Form the Augmented Matrix:**
$$
\left[ \begin{array}{ccc|c}
1 & 2 & 1 & 1 \\
0 & 1 & -1 & 3 \\
2 & 4 & 2 & 2
\end{array} \right]
$$

**2. Perform Row Operations to find RREF:**
After performing $R_3 \gets R_3 - 2R_1$, the third row becomes zeros, showing that the equations were linearly dependent. The RREF result is:
$$
\left[ \begin{array}{ccc|c}
1 & 0 & 3 & -5 \\
0 & 1 & -1 & 3 \\
0 & 0 & 0 & 0
\end{array} \right]
$$

**3. Extract the Solution:**
- $x + 3z = -5 \implies x = -5 - 3z$
- $y - z = 3 \implies y = 3 + z$
- $z$ is a free variable.

The solution set is:
$$
\begin{bmatrix} x \\ y \\ z \end{bmatrix} = 
\begin{bmatrix} -5 \\ 3 \\ 0 \end{bmatrix} + 
z \begin{bmatrix} -3 \\ 1 \\ 1 \end{bmatrix}
$$